### PR TITLE
Support sqe128 cqe32

### PR DESCRIPTION
**Pull request by sungup**
Propose SQE128 and CQE32 for large size SQE and CQE for device passthru commands.

1. Abstract SubmissionQueueEntry and CompletionQueueEvent to interface to serve different size entries.
2. Add flags for SQE128 and CQE32
3. Add SubmissionQueueRing and CompletionQueueRing interface to manage different size of rings.
4. Add an example for the NVMe passthru command using IOURing

This features is valid after Linux kernel 5.19 (that support IOURing interface)

resolved: #21

### CODE REVIEW

**Comment by Iceber** [comment]
@sungup Thanks for your contribution, I will review as soon as possible

**Review by Iceber — APPROVED** [review]
LGTM, Thank you so much for adding this feature!

**Comment by Iceber** [comment]
@sungup I see your implementation using generic type, is it not used here because of the current golang version?

**Comment by sungup** [comment]
@Iceber Yes, I think, Generic implementation has been imported into Go less than 1 year, so little bit fast to apply the generic implementation.

How about your opinion? If generic implementation can be applied into iouring-go, I'll request new PR little bit optimized code. (last version I mentioned in issue #21 is roughly modified codes from this PR)

**Comment by Iceber** [comment]
This pr is good enough, the introduction of generic type doesn't bring very much benefit.

> Yes, I think, Generic implementation has been imported into Go less than 1 year, so little bit fast to apply the generic implementation.

I also think we can do without generic type for now

**Pull request merged**
